"""
Configuration for the Onit CLM Automation Client.

Loads environment variables from .env and defines the dictionary IDs
for the Onit App Builder apps used throughout the automation workflow.

Environment Variables:
    ONIT_BASE_URL  - Base URL of the Onit instance (e.g. https://consumerdir-tst.gold-ab.onit.com)
    ONIT_API_KEY   - API authentication token for the Onit REST API

Dictionary IDs:
    Each "app" in Onit App Builder has a dictionary ID that identifies it.
    These IDs are used when creating or querying records (atoms) in that app.
"""

import os
from dotenv import load_dotenv

load_dotenv()

# Onit API connection
BASE_URL = os.environ["ONIT_BASE_URL"].rstrip("/")
API_KEY = os.environ["ONIT_API_KEY"]

# Dictionary IDs — each maps to an Onit App Builder application
CLM_DICTIONARY_ID = "54b7e691ed404f54990003bf"           # Contract Lifecycle Management (main contracts app)
CONTACTS_DICTIONARY_ID = "5ce59de8d8a1be14f7002d9a"       # Other Party Contacts (contact records linked to contracts)
DOCUMENTS_DICTIONARY_ID = "5c6c79b19fcae642af000086"       # Documents (files attached to contracts, e.g. Order Forms)
SIGNATURE_DICTIONARY_ID = "5d2386add8a1be202a001fbc"       # Send for Signature (triggers HelloSign signature flow)

# AxDraft API connection
AXDRAFT_BASE_URL = os.environ.get("AXDRAFT_BASE_URL", "https://api.axdraft.com")
AXDRAFT_TOKEN = os.environ.get("AXDRAFT_TOKEN", "")
AXDRAFT_DOCUMENT_ID = os.environ.get("AXDRAFT_DOCUMENT_ID", "14897")

# Business constants
ORDER_FORM_DOC_NAME = "Order Form"                          # Document name generated by AxDraft
SIGNATURE_METHOD = "HelloSign"
SIGNER2_NAME = "Sales Operations"
SIGNER2_EMAIL = "orderform@consumerdirect.com"
