"""
Step 3: Send a contract for signature via HelloSign.

After the Order Form document is generated by AxDraft (Step 2), this step
creates a "Send for Signature" atom that triggers HelloSign to send
signature request emails to both signers.

The process:
    1. Fetch the contract atom to read signer name/email and requester
    2. Look up the document ID by searching the Documents app where
       p_parent_id matches the contract (prefers "Order Form" document)
    3. Create a Send for Signature atom with:
       - Signer 1: Other Party Contact (the partner, routing order 1)
       - Signer 2: Sales Operations via email address (routing order 2)
       - The Order Form document linked via r_document_id
       - The contract linked via r_contract_id

After creation, Onit automatically:
    - Moves the contract phase to "Other Party Signatures"
    - Sends HelloSign signature request emails to both signers
    - Sets p_date_sent_for_signature and p_hellosign_id on the contract
"""

from src.api import api_request
from src.config import (
    SIGNATURE_DICTIONARY_ID, SIGNATURE_METHOD,
    SIGNER2_NAME, SIGNER2_EMAIL,
)
from src.lookups import lookup_document_id


def send_for_signature(contract_atom_id: str):
    """Send a contract for signature via HelloSign.

    Reads signer info from the contract, finds the Order Form document,
    and creates a Send for Signature atom with 2 signers.

    Args:
        contract_atom_id: The CLM contract atom ID from Step 1.
    """
    print(f"  [1/3] Fetching contract {contract_atom_id}...")
    result = api_request("GET", f"/api/atoms/{contract_atom_id}.json")
    if not result.get("success"):
        print(f"  FAILED: Could not fetch contract")
        return
    contract = result["data"]

    signer_name = contract.get("p_other_party_contact_name", "")
    signer_email = contract.get("p_other_party_contact_email", "")
    requester_email = contract.get("requester_email", "")

    if not signer_name or not signer_email:
        print(f"  FAILED: Missing signer info on contract")
        return

    print(f"  [2/3] Looking up document...")
    document_id = lookup_document_id(contract_atom_id)
    if not document_id:
        print(f"  FAILED: No document found for contract")
        return
    print(f"        Found: {document_id}")

    print(f"  [3/3] Sending for signature...")
    result = api_request(
        "POST",
        f"/api/atom_dictionaries/{SIGNATURE_DICTIONARY_ID}/atoms",
        body={"atom": {
            "requester_email": requester_email,
            "name": "temp",
            "p_signature_method": SIGNATURE_METHOD,
            "p_number_of_signers": 2,
            "p_user_type_1": "Other Party Contact",
            "p_recipient_name_1": signer_name,
            "p_recipient_email_1": signer_email,
            "p_country_code_1": "1",
            "p_routing_order_1": 1,
            "p_user_type_2": "Email Address",
            "p_recipient_name_2": SIGNER2_NAME,
            "p_recipient_email_2": SIGNER2_EMAIL,
            "p_country_code_2": "1",
            "p_routing_order_2": 2,
            "r_contract_id": contract_atom_id,
            "r_document_id": document_id,
            "p_document_parent_id_for_filter": contract_atom_id,
        }},
    )

    if result.get("success"):
        print(f"        Created: {result.get('data', '')}")
        print(f"        Contract moved to signature phase")
    else:
        print(f"        FAILED: {result.get('message')}")
